ALTER TABLE `properties` ADD `property_category` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `property_id` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `property_status` varchar(50);--> statement-breakpoint
ALTER TABLE `properties` ADD `land_area` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `built_up_area` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `plot_dimensions` varchar(255);--> statement-breakpoint
ALTER TABLE `properties` ADD `zoning` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `land_use` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `development_type` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `layout_name` varchar(255);--> statement-breakpoint
ALTER TABLE `properties` ADD `number_of_units` int;--> statement-breakpoint
ALTER TABLE `properties` ADD `unit_sizes` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `floor_plan` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `road_access` varchar(255);--> statement-breakpoint
ALTER TABLE `properties` ADD `road_width` varchar(50);--> statement-breakpoint
ALTER TABLE `properties` ADD `power_availability` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `water_availability` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `drainage_system` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `sewage_system` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `parking_spaces` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `vehicle_access` varchar(255);--> statement-breakpoint
ALTER TABLE `properties` ADD `amenities` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `infrastructure` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `furnishing_status` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `construction_status` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `government_approvals` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `rera_status` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `dtcp_status` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `cmda_status` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `environmental_clearance` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `legal_verification_status` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `ownership_type` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `title_deed_details` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `tax_status` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `encumbrance_status` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `investment_potential` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `rental_income` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `lease_terms` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `payment_terms` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `price_per_sqft` varchar(50);--> statement-breakpoint
ALTER TABLE `properties` ADD `price_per_acre` varchar(50);--> statement-breakpoint
ALTER TABLE `properties` ADD `market_value_trend` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `connectivity` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `nearby_facilities` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `suitability` varchar(255);--> statement-breakpoint
ALTER TABLE `properties` ADD `project_phase` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `development_stage` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `builder_name` varchar(255);--> statement-breakpoint
ALTER TABLE `properties` ADD `developer_name` varchar(255);--> statement-breakpoint
ALTER TABLE `properties` ADD `contractor_name` varchar(255);--> statement-breakpoint
ALTER TABLE `properties` ADD `maintenance_cost` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `operating_cost` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `risk_assessment` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `compliance_check` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `documents` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `legal_documents` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `approval_documents` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `ownership_proof` text;--> statement-breakpoint
ALTER TABLE `properties` ADD `identity_verification` varchar(100);--> statement-breakpoint
ALTER TABLE `properties` ADD `views_count` int DEFAULT 0;--> statement-breakpoint
ALTER TABLE `properties` ADD CONSTRAINT `properties_property_id_unique` UNIQUE(`property_id`);--> statement-breakpoint
CREATE INDEX `property_id_idx` ON `properties` (`property_id`);--> statement-breakpoint
CREATE INDEX `property_category_idx` ON `properties` (`property_category`);--> statement-breakpoint
CREATE INDEX `property_status_idx` ON `properties` (`property_status`);