import { db } from '../src/server/db/client.js';
import { properties } from '../src/server/db/schema.js';

const tamilNaduProperties = [
  {
    // Chennai - Luxury Villa
    title: 'Premium 4BHK Villa in OMR, Chennai',
    propertyCategory: 'Residential',
    type: 'Villa',
    location: 'Chennai, Tamil Nadu',
    address: 'Old Mahabalipuram Road (OMR), Sholinganallur, Chennai - 600119',
    propertyId: 'TN-CHN-001',
    propertyStatus: 'Sale',
    landArea: '2400 sq.ft',
    builtUpArea: '3200 sq.ft',
    area: '3200 sq.ft',
    plotDimensions: '40x60 feet',
    zoning: 'Residential',
    landUse: 'Residential',
    developmentType: 'Gated Community',
    layoutName: 'Prestige Oasis',
    numberOfUnits: 50,
    unitSizes: '2400-3500 sq.ft',
    floorPlan: '4 Bedrooms, 5 Bathrooms, Living, Dining, Kitchen, Servant Room',
    roadAccess: 'Main Road',
    roadWidth: '60 feet',
    powerAvailability: 'Available - 3 Phase',
    waterAvailability: 'Available - Borewell + Corporation',
    drainageSystem: 'Underground Drainage',
    sewageSystem: 'STP Available',
    parkingSpaces: '2 Covered + 2 Open',
    vehicleAccess: '4 Wheeler Access',
    amenities: 'Swimming Pool, Gym, Clubhouse, Children Play Area, 24/7 Security, Power Backup, Landscaped Gardens',
    infrastructure: 'Modular Kitchen, Wooden Flooring, False Ceiling, Branded Fittings',
    furnishingStatus: 'Semi-furnished',
    constructionStatus: 'Ready to Move',
    governmentApprovals: 'CMDA Approved, RERA Registered',
    reraStatus: 'Approved - TN/RERA/2023/001234',
    dtcpStatus: 'Approved',
    cmdaStatus: 'Approved',
    environmentalClearance: 'Obtained',
    legalVerificationStatus: 'Verified - Clear Title',
    ownershipType: 'Freehold',
    titleDeedDetails: 'Clear title with proper documentation',
    taxStatus: 'Clear - Property Tax Paid',
    encumbranceStatus: 'Clear',
    investmentPotential: 'High - IT Corridor area with excellent appreciation potential',
    rentalIncome: '₹80,000 - ₹1,00,000 per month',
    leaseTerms: 'Available for lease - Minimum 11 months',
    price: '₹2,80,00,000',
    paymentTerms: 'Negotiable - Bank Loan Available',
    pricePerSqft: '₹8,750',
    pricePerAcre: 'N/A',
    marketValueTrend: 'Rising',
    description: 'Luxurious 4BHK villa in premium gated community on OMR. Features modern architecture, high-end finishes, and world-class amenities. Perfect for families looking for upscale living in Chennai\'s IT corridor.',
    connectivity: 'OMR Main Road - 500m, Tidel Park - 3km, Chennai Airport - 12km, Siruseri IT Park - 5km, ECR Beach - 8km',
    nearbyFacilities: 'Schools: PSBB, Chettinad Vidyashram (2km), Hospitals: Kauvery Hospital (1.5km), Malls: Phoenix Marketcity (4km), IT Parks: Multiple within 5km',
    suitability: 'Residential - Luxury Living',
    projectPhase: 'Phase 2',
    developmentStage: 'Completed',
    builderName: 'Prestige Group',
    developerName: 'Prestige Estates Projects Ltd',
    contractorName: 'L&T Construction',
    maintenanceCost: '₹8,000 per month',
    operatingCost: '₹15,000 per month (including utilities)',
    riskAssessment: 'Low Risk - Established builder, prime location',
    complianceCheck: 'All compliances met - CMDA, RERA, Fire Safety',
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    images: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    documents: 'Sale Deed, Encumbrance Certificate, Tax Receipts',
    legalDocuments: 'Title Deed, EC for 30 years, Legal Opinion',
    approvalDocuments: 'CMDA Approval, RERA Certificate, Occupancy Certificate',
    ownershipProof: 'Sale Deed, Patta, Chitta',
    ownerName: 'Rajesh Kumar',
    ownerPhone: '+91 98400 12345',
    ownerEmail: 'rajesh.kumar@example.com',
    ownerAddress: 'Chennai, Tamil Nadu',
    identityVerification: 'Verified - Aadhaar, PAN',
    viewsCount: 0,
    tokenCost: 5,
    isActive: true,
    status: 'Available',
  },
  {
    // Coimbatore - Commercial Property
    title: '5000 sq.ft Commercial Space in RS Puram, Coimbatore',
    propertyCategory: 'Commercial',
    type: 'Office Space',
    location: 'Coimbatore, Tamil Nadu',
    address: 'RS Puram Main Road, Coimbatore - 641002',
    propertyId: 'TN-CBE-002',
    propertyStatus: 'Rent',
    landArea: 'N/A',
    builtUpArea: '5000 sq.ft',
    area: '5000 sq.ft',
    plotDimensions: 'Ground + First Floor',
    zoning: 'Commercial',
    landUse: 'Commercial',
    developmentType: 'Standalone Building',
    layoutName: 'RS Puram Commercial Complex',
    numberOfUnits: 1,
    unitSizes: '5000 sq.ft',
    floorPlan: 'Open Plan Office Space with 2 Conference Rooms, Reception, Pantry, 4 Washrooms',
    roadAccess: 'Main Road',
    roadWidth: '80 feet',
    powerAvailability: 'Available - 3 Phase with 100 KVA Backup',
    waterAvailability: 'Available - Corporation + Borewell',
    drainageSystem: 'Underground Drainage',
    sewageSystem: 'Connected to Corporation',
    parkingSpaces: '15 Cars',
    vehicleAccess: '4 Wheeler + Goods Vehicle Access',
    amenities: 'Lift, Power Backup, Security, Cafeteria, Conference Rooms',
    infrastructure: 'Centralized AC, False Ceiling, Modular Workstations Ready',
    furnishingStatus: 'Semi-furnished',
    constructionStatus: 'Ready to Occupy',
    governmentApprovals: 'Corporation Approved',
    reraStatus: 'Not Applicable',
    dtcpStatus: 'Approved',
    cmdaStatus: 'Not Applicable',
    environmentalClearance: 'Not Required',
    legalVerificationStatus: 'Verified',
    ownershipType: 'Freehold',
    titleDeedDetails: 'Clear commercial title',
    taxStatus: 'Clear',
    encumbranceStatus: 'Clear',
    investmentPotential: 'Medium - Prime commercial location',
    rentalIncome: '₹2,50,000 per month',
    leaseTerms: 'Minimum 3 years lease, 10 months advance',
    price: '₹2,50,000 per month',
    paymentTerms: '10 months advance + Monthly rent',
    pricePerSqft: '₹50 per sq.ft per month',
    pricePerAcre: 'N/A',
    marketValueTrend: 'Stable',
    description: 'Premium commercial office space in the heart of RS Puram, Coimbatore\'s prime business district. Ideal for IT companies, corporate offices, or professional services. Excellent connectivity and visibility.',
    connectivity: 'RS Puram Junction - 500m, Coimbatore Airport - 8km, Railway Station - 3km, Bus Stand - 2km',
    nearbyFacilities: 'Banks: All major banks within 500m, Restaurants: Multiple options, Hotels: 5-star hotels nearby, Shopping: Brookefields Mall (2km)',
    suitability: 'Commercial - Office Space',
    projectPhase: 'N/A',
    developmentStage: 'Completed',
    builderName: 'Private Owner',
    developerName: 'N/A',
    contractorName: 'N/A',
    maintenanceCost: '₹25,000 per month',
    operatingCost: '₹50,000 per month (including AC, utilities)',
    riskAssessment: 'Low Risk - Prime location, established area',
    complianceCheck: 'All commercial compliances met',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    images: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    documents: 'Lease Agreement Template, Tax Receipts',
    legalDocuments: 'Title Deed, EC, NOC',
    approvalDocuments: 'Building Plan Approval, Occupancy Certificate',
    ownershipProof: 'Sale Deed, Patta',
    ownerName: 'Suresh Textiles Pvt Ltd',
    ownerPhone: '+91 98400 23456',
    ownerEmail: 'suresh.textiles@example.com',
    ownerAddress: 'Coimbatore, Tamil Nadu',
    identityVerification: 'Verified - Company Registration, GST',
    viewsCount: 0,
    tokenCost: 4,
    isActive: true,
    status: 'Available',
  },
  {
    // Madurai - Agricultural Land
    title: '5 Acres Agricultural Land near Madurai',
    propertyCategory: 'Agricultural',
    type: 'Agricultural Land',
    location: 'Madurai, Tamil Nadu',
    address: 'Thiruparankundram Road, Madurai - 625005',
    propertyId: 'TN-MDU-003',
    propertyStatus: 'Sale',
    landArea: '5 Acres (2,17,800 sq.ft)',
    builtUpArea: 'N/A',
    area: '5 Acres',
    plotDimensions: '300x726 feet (approx)',
    zoning: 'Agricultural',
    landUse: 'Agriculture',
    developmentType: 'Open Land',
    layoutName: 'N/A',
    numberOfUnits: 1,
    unitSizes: '5 Acres',
    floorPlan: 'N/A',
    roadAccess: 'Tar Road',
    roadWidth: '20 feet',
    powerAvailability: 'Available - EB Connection',
    waterAvailability: 'Borewell + Canal Irrigation',
    drainageSystem: 'Natural Drainage',
    sewageSystem: 'N/A',
    parkingSpaces: 'N/A',
    vehicleAccess: 'Tractor + 4 Wheeler Access',
    amenities: 'Borewell, EB Connection, Fencing',
    infrastructure: 'Level Land, Red Soil',
    furnishingStatus: 'N/A',
    constructionStatus: 'N/A',
    governmentApprovals: 'Patta Available',
    reraStatus: 'Not Applicable',
    dtcpStatus: 'Not Applicable',
    cmdaStatus: 'Not Applicable',
    environmentalClearance: 'Not Required',
    legalVerificationStatus: 'Verified - Clear Title',
    ownershipType: 'Freehold - Patta Land',
    titleDeedDetails: 'Clear agricultural patta',
    taxStatus: 'Clear',
    encumbranceStatus: 'Clear',
    investmentPotential: 'High - Near city limits, conversion potential',
    rentalIncome: 'N/A',
    leaseTerms: 'Available for lease - Agricultural purposes',
    price: '₹75,00,000',
    paymentTerms: 'Negotiable',
    pricePerSqft: 'N/A',
    pricePerAcre: '₹15,00,000 per acre',
    marketValueTrend: 'Rising',
    description: 'Prime 5-acre agricultural land near Madurai city limits. Excellent for farming, horticulture, or future investment. Good water availability with borewell and canal irrigation. Clear patta land with all documents.',
    connectivity: 'Madurai City - 8km, Thiruparankundram Temple - 3km, NH 44 - 5km, Airport - 15km',
    nearbyFacilities: 'Villages nearby, Agricultural market - 5km, Banks in Thiruparankundram',
    suitability: 'Agriculture, Farm House, Investment',
    projectPhase: 'N/A',
    developmentStage: 'N/A',
    builderName: 'N/A',
    developerName: 'N/A',
    contractorName: 'N/A',
    maintenanceCost: 'Minimal',
    operatingCost: 'Based on cultivation',
    riskAssessment: 'Low Risk - Clear title, good location',
    complianceCheck: 'Agricultural land - No specific compliance required',
    imageUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800',
    images: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800',
    documents: 'Patta, Chitta, FMB Sketch',
    legalDocuments: 'Sale Deed, EC for 30 years, Legal Opinion',
    approvalDocuments: 'Patta Document',
    ownershipProof: 'Patta, Adangal',
    ownerName: 'Murugan Nadar',
    ownerPhone: '+91 98400 34567',
    ownerEmail: 'murugan.nadar@example.com',
    ownerAddress: 'Madurai, Tamil Nadu',
    identityVerification: 'Verified - Aadhaar, PAN',
    viewsCount: 0,
    tokenCost: 3,
    isActive: true,
    status: 'Available',
  },
  {
    // Trichy - Residential Plot
    title: '2400 sq.ft DTCP Approved Plot in Trichy',
    propertyCategory: 'Residential',
    type: 'Plot',
    location: 'Tiruchirappalli (Trichy), Tamil Nadu',
    address: 'KK Nagar, Tiruchirappalli - 620021',
    propertyId: 'TN-TRY-004',
    propertyStatus: 'Sale',
    landArea: '2400 sq.ft',
    builtUpArea: 'N/A',
    area: '2400 sq.ft',
    plotDimensions: '40x60 feet',
    zoning: 'Residential',
    landUse: 'Residential',
    developmentType: 'Approved Layout',
    layoutName: 'KK Nagar Extension',
    numberOfUnits: 120,
    unitSizes: '1200-3000 sq.ft',
    floorPlan: 'N/A - Vacant Plot',
    roadAccess: 'Tar Road',
    roadWidth: '30 feet',
    powerAvailability: 'Available - EB Post',
    waterAvailability: 'Corporation Water + Borewell',
    drainageSystem: 'Underground Drainage',
    sewageSystem: 'Corporation Sewage',
    parkingSpaces: 'N/A',
    vehicleAccess: '4 Wheeler Access',
    amenities: 'Street Lights, Underground Drainage, Water Supply',
    infrastructure: 'Tar Roads, Avenue Plantation',
    furnishingStatus: 'N/A',
    constructionStatus: 'N/A',
    governmentApprovals: 'DTCP Approved Layout',
    reraStatus: 'Not Applicable',
    dtcpStatus: 'Approved - Layout Plan No: TRY/2022/1234',
    cmdaStatus: 'Not Applicable',
    environmentalClearance: 'Not Required',
    legalVerificationStatus: 'Verified - Clear Title',
    ownershipType: 'Freehold',
    titleDeedDetails: 'Clear residential plot title',
    taxStatus: 'Clear',
    encumbranceStatus: 'Clear',
    investmentPotential: 'Medium - Established residential area',
    rentalIncome: 'N/A',
    leaseTerms: 'N/A',
    price: '₹48,00,000',
    paymentTerms: 'Negotiable - Bank Loan Available',
    pricePerSqft: '₹2,000',
    pricePerAcre: 'N/A',
    marketValueTrend: 'Stable',
    description: 'DTCP approved residential plot in well-established KK Nagar area. Ready for construction with all approvals in place. Good connectivity to schools, hospitals, and shopping areas. Ideal for building your dream home.',
    connectivity: 'Trichy Junction - 5km, Airport - 8km, Bus Stand - 4km, NH 83 - 2km',
    nearbyFacilities: 'Schools: Bishop Heber, Campion (1km), Hospitals: Apollo, Kauvery (2km), Malls: Femina Shopping Mall (3km)',
    suitability: 'Residential - Individual House Construction',
    projectPhase: 'N/A',
    developmentStage: 'Approved Layout',
    builderName: 'KK Nagar Developers',
    developerName: 'KK Nagar Developers Pvt Ltd',
    contractorName: 'N/A',
    maintenanceCost: 'N/A',
    operatingCost: 'N/A',
    riskAssessment: 'Low Risk - DTCP approved, established area',
    complianceCheck: 'DTCP approved layout',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
    images: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
    documents: 'Sale Deed, Layout Plan, DTCP Approval',
    legalDocuments: 'Sale Deed, EC, Legal Opinion',
    approvalDocuments: 'DTCP Layout Approval',
    ownershipProof: 'Sale Deed, Patta',
    ownerName: 'Lakshmi Sundaram',
    ownerPhone: '+91 98400 45678',
    ownerEmail: 'lakshmi.sundaram@example.com',
    ownerAddress: 'Tiruchirappalli, Tamil Nadu',
    identityVerification: 'Verified - Aadhaar, PAN',
    viewsCount: 0,
    tokenCost: 3,
    isActive: true,
    status: 'Available',
  },
  {
    // Salem - Industrial Land
    title: '2 Acres Industrial Land in SIPCOT, Salem',
    propertyCategory: 'Industrial',
    type: 'Industrial Land',
    location: 'Salem, Tamil Nadu',
    address: 'SIPCOT Industrial Park, Veerapandi, Salem - 636005',
    propertyId: 'TN-SLM-005',
    propertyStatus: 'Sale',
    landArea: '2 Acres (87,120 sq.ft)',
    builtUpArea: 'N/A',
    area: '2 Acres',
    plotDimensions: '200x436 feet (approx)',
    zoning: 'Industrial',
    landUse: 'Industrial',
    developmentType: 'Industrial Park',
    layoutName: 'SIPCOT Salem',
    numberOfUnits: 1,
    unitSizes: '2 Acres',
    floorPlan: 'N/A - Vacant Land',
    roadAccess: 'Concrete Road',
    roadWidth: '60 feet',
    powerAvailability: 'Available - HT Connection, 500 KVA',
    waterAvailability: 'Available - SIPCOT Water Supply + Borewell',
    drainageSystem: 'Industrial Drainage',
    sewageSystem: 'SIPCOT Sewage Treatment',
    parkingSpaces: 'N/A',
    vehicleAccess: 'Heavy Vehicle Access',
    amenities: 'Security, Street Lights, Fire Station, Pollution Control',
    infrastructure: 'Concrete Roads, Compound Wall, EB Connection',
    furnishingStatus: 'N/A',
    constructionStatus: 'N/A',
    governmentApprovals: 'SIPCOT Approved, Pollution Control Board NOC',
    reraStatus: 'Not Applicable',
    dtcpStatus: 'Not Applicable',
    cmdaStatus: 'Not Applicable',
    environmentalClearance: 'Required - Can be obtained',
    legalVerificationStatus: 'Verified - Clear Title',
    ownershipType: 'Freehold - SIPCOT Allotment',
    titleDeedDetails: 'SIPCOT allotment letter and sale deed',
    taxStatus: 'Clear',
    encumbranceStatus: 'Clear',
    investmentPotential: 'High - Industrial growth area',
    rentalIncome: 'N/A',
    leaseTerms: 'Available for lease to manufacturing units',
    price: '₹1,20,00,000',
    paymentTerms: 'Negotiable - Bank Loan Available',
    pricePerSqft: '₹138',
    pricePerAcre: '₹60,00,000 per acre',
    marketValueTrend: 'Rising',
    description: 'Prime 2-acre industrial land in SIPCOT Salem Industrial Park. Ideal for manufacturing units, warehouses, or logistics operations. Excellent infrastructure with HT power, water supply, and heavy vehicle access. All necessary approvals in place.',
    connectivity: 'Salem City - 12km, NH 44 - 3km, Railway Station - 10km, Airport - 140km (Coimbatore)',
    nearbyFacilities: 'Industrial units nearby, Banks, Restaurants, Fuel stations within SIPCOT',
    suitability: 'Industrial - Manufacturing, Warehouse, Logistics',
    projectPhase: 'N/A',
    developmentStage: 'Approved Industrial Land',
    builderName: 'SIPCOT',
    developerName: 'State Industries Promotion Corporation of Tamil Nadu',
    contractorName: 'N/A',
    maintenanceCost: 'SIPCOT Maintenance Charges Apply',
    operatingCost: 'Based on industrial activity',
    riskAssessment: 'Low Risk - Government approved industrial park',
    complianceCheck: 'SIPCOT compliances, Pollution Control Board approval required',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
    images: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
    documents: 'SIPCOT Allotment Letter, Sale Deed, Layout Plan',
    legalDocuments: 'Sale Deed, EC, SIPCOT NOC',
    approvalDocuments: 'SIPCOT Approval, PCB NOC',
    ownershipProof: 'Sale Deed, SIPCOT Allotment',
    ownerName: 'Salem Industries Ltd',
    ownerPhone: '+91 98400 56789',
    ownerEmail: 'salem.industries@example.com',
    ownerAddress: 'Salem, Tamil Nadu',
    identityVerification: 'Verified - Company Registration, GST',
    viewsCount: 0,
    tokenCost: 4,
    isActive: true,
    status: 'Available',
  },
];

async function addTamilNaduProperties() {
  try {
    console.log('=== Adding Tamil Nadu Properties ===\n');

    for (const property of tamilNaduProperties) {
      const result = await db.insert(properties).values(property);
      console.log(`✓ Added: ${property.title}`);
      console.log(`  Location: ${property.location}`);
      console.log(`  Property ID: ${property.propertyId}`);
      console.log(`  Price: ${property.price}`);
      console.log(`  Token Cost: ${property.tokenCost}`);
      console.log('');
    }

    console.log('=== All Tamil Nadu Properties Added Successfully ===');
    process.exit(0);
  } catch (error) {
    console.error('Error adding properties:', error);
    process.exit(1);
  }
}

addTamilNaduProperties();
